source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxCocoaTouch_Example', :exclusive => true do
  pod "RxCocoaTouch", :path => "../"
  
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => '2.0-alpha.1'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => '2.0-alpha.1'
end

target 'RxCocoaTouch_Tests', :exclusive => true do
  pod "RxCocoaTouch", :path => "../"

  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => '2.0-alpha.1'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => '2.0-alpha.1'
end
